version: '3.8'


services:
  omi_pg:
    image: postgres
    container_name: omi_pg
    volumes:
      - ./docker/pg_init:/docker-entrypoint-initdb.d
      - "/omi_pg_data/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=$PGUSE
      - POSTGRES_PASSWORD=$PGPASSWORD
#      - POSTGRES_DB=breakfast
      - POSTGRES_MULTIPLE_DATABASES=breakfast, mesure, applied
    ports:
      - 5432:5432

  omi:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: omi
    depends_on:
      - omi_pg
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - SPRING_DATASOURCE_URL="jdbc:postgresql://${PGHOST}:${PGPORT}/${PGBREAKFAST}"
      - SPRING_DATASOURCE_USERNAME="$PGUSER"
      - SPRING_DATASOURCE_PASSWORD="$PGPASSWORD"
      - SPRING_PROFILES_ACTIVE=production
      - APP_DATASOURCE_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGBREAKFAST}"
      - APP_DATASOURCE_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGMESURE}"
      - APP_DATASOURCE_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDRAFTER}"
    ports:
      - 8080:8080
    env_file:
      - .env
