#spring.h2.console.enabled=true
#logging.level.org.springframework.jdbc=DEBUG
#spring.datasource.generate-unique-name=false

logging:
  level:
    org:
      springframework:
        jdbc : DEBUG


openai:
  api-key: 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

spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    # Breakfast - Scraping App
    breakfast:
      url: jdbc:postgresql://localhost:5432/breakfast
      username: postgres
      password: password
    # Mesure - Food Cost App
    mesure:
      url: jdbc:postgresql://localhost:5432/mesure
      username: postgres
      password: password
  #  h2:
#    console:
#      enabled: true
#  datasource:
#    generate-unique-name: false
#    breakfast:
#      url: jdbc:h2:mem:breakfast
#      name: breakfast
#    mesure:
#      url: jdbc:h2:mem:mesure
#      name: mesure
  sql:
    init:
      mode: always




