version: '3.8'

services:
  omi_pg:
#  omi_breakfast:
    image: 'postgres:alpine'
    restart: always
#    expose:
#        - 5432
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
        # reference to https://dev.to/bgord/multiple-postgres-databases-in-a-single-docker-container-417l
        # github: https://github.com/mrts/docker-postgresql-multiple-databases
        # @see: ./pg_init/multi_database.sh - create multiple databases
        # @see: ./pg_init/init.sql - create databases
      - ./pg_init:/docker-entrypoint-initdb.d # Load init scripts
    environment:
#      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: breakfast,mesure # Create multiple databases

#  omi_mesure:
#    image: 'postgres:alpine'
#    container_name: omi_mesure
#    ports:
#      - '5433:5432'
#    volumes:
#      - ./postgres-data2:/var/lib/postgresql/data
#    environment:
#      PGDATABASE: postgres
#      PGUSERNAME: postgres
#      PGPASSWORD: password

  # 1. Go to http://localhost:5050
  # 2. Login with the following credentials: login: admin@locahost.com, pwd: admin
  # 3. Create new server:
    #    - Name: name you want
    #    - Go to connection tab then fill Host/Address with IP address of the docker (omi_pg)
    #      - 1. docker ps -a -> find omi_pg pid
    #      - 2. docker inspect <pid> | grep IPAddress -> find the IP address e.g.: 172.0.x.x
    #    - Paste the IP address in the Host/Address field
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
