version: '3.8'

services:
  omi_pg:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
        # reference to https://dev.to/bgord/multiple-postgres-databases-in-a-single-docker-container-417l
        # github: https://github.com/mrts/docker-postgresql-multiple-databases
        - ./pg_init:/docker-entrypoint-initdb.d # Load init scripts
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: Breakfast, Mesure # Create multiple databases


  # 1. Go to http://localhost:5050
  # 2. Login with the following credentials: login: admin@locahost.com, pwd: admin
  # 3. Create new server:
    #    - Name: name you want
    #    - Go to connection tab then fill Host/Address with IP address of the docker (yuendim_pg)
    #      - 1. docker ps -a -> find yuendim_pg pid
    #      - 2. docker inspect <pid> | grep IPAddress -> find the IP address e.g.: 172.0.x.x
    #    - Paste the IP address in the Host/Address field
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
