#spring.h2.console.enabled=true
#logging.level.org.springframework.jdbc=DEBUG
#spring.datasource.generate-unique-name=false

logging:
  level:
    org:
      springframework:
        jdbc : DEBUG
spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    breakfast:
      url: jdbc:h2:mem:breakfast
      name: breakfast
    mesure:
      url: jdbc:h2:mem:mesure
      name: mesure
  sql:
    init:
      mode: always




# Breakfast - Scraping App
#spring.datasource.
#spring.datasource.name=breakfast
# Mesure - Food Cost App
#spring.datasource.name=mesure
